CREATE DATABASE IF NOT EXISTS temp;
USE TEMP;

CREATE TABLE ACCOUNT(
ID INT PRIMARY KEY,
name varchar(255) unique,
balance int NOT NULL DEFAULT 0
);
INSERT INTO ACCOUNT(ID,NAME) VALUES
(1,'A');
-- ADD NEW COLUMN
ALTER TABLE ACCOUNT ADD INTEREST FLOAT NOT NULL DEFAULT 0;
-- MODIFY COLUMN DATA TYPE 
ALTER TABLE ACCOUNT MODIFY INTEREST DOUBLE NOT NULL DEFAULT 0;
DESC ACCOUNT;
-- RENAME COLUMN 
ALTER TABLE ACCOUNT CHANGE COLUMN  INTEREST SAVING_INTEREST FLOAT NOT NULL DEFAULT 0; 
-- DROP COLUMN 
ALTER TABLE ACCOUNT DROP COLUMN SAVING_INTEREST;
-- RENAME TABLE
ALTER TABLE ACCOUNT RENAME TO ACCOUNT_DETAILS;