CREATE DATABASE IF NOT EXISTS organization;
CREATE DATABASE IF NOT EXISTS temp;
USE TEMP;
USE organization;
CREATE TABLE CUSTOMER(
ID INTEGER NOT NULL PRIMARY KEY,
CNAME VARCHAR(25),
ADDRESS VARCHAR(25),
GENDER CHAR(2),
CITY VARCHAR(150),
PINCODE INTEGER
);
CREATE TABLE ACCOUNT(
ID INT PRIMARY KEY,
name varchar(255) unique,
balance int NOT NULL DEFAULT 0
);
DROP TABLE ACCOUNT;
INSERT INTO ACCOUNT(ID,NAME) VALUES
(1,'A');

INSERT INTO CUSTOMER (ID,CNAME,ADDRESS,GENDER,CITY,PINCODE) VALUES
(1250,"KUNAL","AYODHYA","M","UP",232322),
(1251,"BALRAM","LUCKNOW","M","UP",232321),
(1252,"LAKSHMI","JHANSI","F","UP",232332),
(1253,"CHAMPA","TAMIL","F","TAMIL",230122),
(1254,"MADHUSUDAN","AYODHYA","M","UP",232302);

CREATE TABLE ORDER_DETAILS(
ORDER_ID INTEGER PRIMARY KEY ,
DELIVERY_DATE DATE,
CUST_ID INT,
FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(ID)
);

