CREATE DATABASE IF NOT EXISTS organization;
CREATE DATABASE IF NOT EXISTS temp;
USE TEMP;
USE organization;
CREATE TABLE CUSTOMER(
ID INTEGER NOT NULL PRIMARY KEY,
CNAME VARCHAR(25),
ADDRESS VARCHAR(25),
GENDER CHAR(2),
CITY VARCHAR(150),
PINCODE INTEGER
);
-- SOME VALUE NOT FULL INFO SET DEFAULT NULL
INSERT INTO CUSTOMER (ID,CNAME) VALUES 
(123,"RAM KUMAR");
-- UPDATE DATA 
UPDATE CUSTOMER SET ADDRESS="UP",GENDER='M' WHERE ID=123;
-- UPDATE MULTI ROW DATA 
SET SQL_SAFE_UPDATES=1;
UPDATE CUSTOMER SET PINCODE=23234254;
-- DELETE ROW OR DATA 
DELETE FROM CUSTOMER WHERE ID=1253;
-- DELETE ALL ROW OR DATA IN TABLE
DELETE FROM CUSTOMER;


SELECT * FROM CUSTOMER;
