CREATE DATABASE IF NOT EXISTS organization;
CREATE DATABASE IF NOT EXISTS temp;
USE TEMP;
USE organization;
CREATE TABLE CUSTOMER(
ID INTEGER NOT NULL PRIMARY KEY,
CNAME VARCHAR(25),
ADDRESS VARCHAR(25),
GENDER CHAR(2),
CITY VARCHAR(150),
PINCODE INTEGER
);
-- SOME VALUE NOT FULL INFO SET DEFAULT NULL
INSERT INTO CUSTOMER (ID,CNAME) VALUES 
(123,"RAM KUMAR");
-- UPDATE DATA 
UPDATE CUSTOMER SET ADDRESS="UP",GENDER='M' WHERE ID=123;
-- UPDATE MULTI ROW DATA 
SET SQL_SAFE_UPDATES=1;
UPDATE CUSTOMER SET PINCODE=23234254;
-- DELETE ROW OR DATA 
DELETE FROM CUSTOMER WHERE ID=1253;
-- DELETE ALL ROW OR DATA IN TABLE
DELETE FROM CUSTOMER;


SELECT * FROM CUSTOMER;

-- ON DELETE CASCADE AND ON DELETE NULL 
CREATE DATABASE IF NOT EXISTS ecommerce;
USE ECOMMERCE;
CREATE TABLE CUSTOMER(
ID INTEGER NOT NULL PRIMARY KEY,
CNAME VARCHAR(25),
ADDRESS VARCHAR(25),
GENDER CHAR(2),
CITY VARCHAR(150),
PINCODE INTEGER
);
-- SOME VALUE NOT FULL INFO SET DEFAULT NULL
INSERT INTO CUSTOMER (ID,CNAME,ADDRESS,GENDER,CITY,PINCODE) VALUES 
(123,"RAM KUMAR","AYODHYA",'M',"UP",243232);

CREATE TABLE ORDER_DETAILS(
ORDER_ID INTEGER PRIMARY KEY ,
DELIVERY_DATE DATE,
CUST_ID INT,
FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(ID) ON DELETE CASCADE
);
CREATE TABLE ORDER_DETAILS(
ORDER_ID INTEGER PRIMARY KEY ,
DELIVERY_DATE DATE,
CUST_ID INT,
FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(ID) ON DELETE SET NULL
);

INSERT INTO ORDER_DETAILS (ORDER_ID,DELIVERY_DATE,CUST_ID) VALUES
(2,'2024-03-02',123);

SELECT * FROM CUSTOMER;
SELECT * FROM ORDER_DETAILS;

DELETE FROM CUSTOMER WHERE ID=123; -- IT CAN NOT DELETE FROM PARENT TABLE
-- REPLACE THE DATA (ONLY REPLACE THAT VALUE YOU CHANGED AND OTHER VALUE SET BY DEFAULT NULL)
REPLACE INTO CUSTOMER (ID,CNAME,CITY) VALUES
(1122,'NEWUSER','AYODHYA');

-- This will return rows when there is a match in both tables.
SELECT CUSTOMER.ID, CUSTOMER.CNAME,CUSTOMER.CITY, ORDER_DETAILS.ORDER_ID, ORDER_DETAILS.DELIVERY_DATE
FROM CUSTOMER
INNER JOIN ORDER_DETAILS ON CUSTOMER.ID = ORDER_DETAILS.CUST_ID;

-- Left Join (or Left Outer Join) 
SELECT CUSTOMER.ID, CUSTOMER.CNAME,CUSTOMER.CITY, ORDER_DETAILS.ORDER_ID, ORDER_DETAILS.DELIVERY_DATE
FROM CUSTOMER
LEFT JOIN ORDER_DETAILS ON CUSTOMER.ID = ORDER_DETAILS.CUST_ID;

-- Right Join (or Right Outer Join)
SELECT CUSTOMER.ID, CUSTOMER.CNAME,CUSTOMER.CITY, ORDER_DETAILS.ORDER_ID, ORDER_DETAILS.DELIVERY_DATE
FROM CUSTOMER
RIGHT JOIN ORDER_DETAILS ON CUSTOMER.ID = ORDER_DETAILS.CUST_ID;

-- Full Join (or Full Outer Join)
SELECT C.* ,O.* 
FROM CUSTOMER AS C
LEFT JOIN  ORDER_DETAILS AS O ON C.ID = O.CUST_ID UNION SELECT C.* ,O.* 
FROM CUSTOMER AS C
RIGHT JOIN  ORDER_DETAILS AS O ON C.ID = O.CUST_ID;

-- Cross Join
SELECT CUSTOMER.ID, CUSTOMER.CNAME, ORDER_DETAILS.ORDER_ID, ORDER_DETAILS.DELIVERY_DATE
FROM CUSTOMER
CROSS JOIN ORDER_DETAILS;